# Generated by Django 5.1.2 on 2024-10-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='normal', max_length=16),
        ),
    ]
